services:
  app:
    build: .
    container_name: difotoin-dashboard
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Asia/Jakarta
      - PORT=3000
    volumes:
      - ./data:/app/data:Z    # penting di Alma/RHEL (SELinux)
    ports:
      - "8080:3000"
